Adding Github Actions to Cellveyor and an image folder
GatorEducator/cellveyor pull request #24
Opened 2023-11-07 01:06 UTC by KevenDuverglas

This will allow celllveyor to have its pretty little green checkmark

2023-11-13 16:28 UTC, gkapfham requested changes
Hello @KevenDuverglas, thanks for creating this PR!

Please note that several parts of the documentation need to be generalized further so that the command it not customized to either a specific directory structure or to specific spreadsheets.

It is also worth noting that you are proposing to add a wide variety of binary files to this repository. We cannot allow these type of derived files into the repository. Please chat with Sabrina as she can explain how these files got into the repository in the first place and what we can do to prevent this from happening in the future.

2023-11-13 16:28 UTC, gkapfham commented on README.md
> +[![build](https://github.com/KevenDuverglas/keven-cellveyor/actions/workflows/build.yml/badge.svg)](https://https://github.com/KevenDuverglas/keven-cellveyor/actions/workflows/build.yml)
Hi @KevenDuverglas, you need to make sure that the documentation does not link to a badge that is inside of a repository in your account.

2023-11-13 16:28 UTC, gkapfham commented on README.md
> +CMPSC-203-Fall-2023-Gradebook.xlsx \
This should be further generalized.

It should not, ultimately, have anything to do with our class.

2023-11-13 16:28 UTC, gkapfham commented on README.md
> +--feedback-file /home/gkapfham/working/teaching/github-classroom/
All of these paths need to be generalize and clarified.

2023-11-14 19:51 UTC, jnormile requested changes
@KevenDuverglas, I'm still seeing a lot of derived binary files (like the ones that end with a `.pyc` extension, for example). Whenever you get a chance, please remove these from the PR--thanks!

2023-11-17 14:49 UTC, jnormile approved these changes
Great work putting the GH Actions together, and thanks for taking the time to start us off with a passing build!

Reach out to your peers to get the required reviews--and ask @gkapfham to update his review since he requested changes--and then we'll be good to go! Thanks!

2023-11-17 14:58 UTC, hayleepierce approved these changes
This looks great! Thank you for all your work on this issue!

2023-11-21 20:45 UTC, gkapfham approved these changes
Hello @KevenDuverglas and @jnormile, I am willing to approve this PR and see it merged into our project. With that said, @KevenDuverglas, there are two points that I wanted to raise after discussing them with @jnormile.

1. It is generally not a good idea to have a top-level directory called `spreadsheets` that is not essential for the use of this tool. I think that it would be better if this directory was either a "dot directory" that was hidden or if it was, for instance, inside of the `.github` directory or in a special `testing` directory.
2. It is also important to point out that right now there is a `feedback.yml` file that is inside of the `spreadsheets` directory which does not make sense because of the fact that a YML file is not a spreadsheet.

With that said, perhaps we can agree to overlook those issues right now so that we can merge this content and then revise things later as needed.

2023-11-21 20:46 UTC, merged